--- Makefile
+++ Makefile
@@ -18,14 +18,7 @@ options:
 	@echo CC $<
 	@${CC} -c ${CFLAGS} $<
 
-${OBJ}: config.h config.mk filters_compiled
-
-filters_compiled: filters
-	sed -e '/^$$/d' -e 's|\\|\\\\|g' -e 's|$$|",|' -e 's|^|"|' < filters > $@
-
-filters:
-	@echo creating $@ from filters.def
-	@cp filters.def $@
+${OBJ}: config.h config.mk
 
 config.h:
 	@echo creating $@ from config.def.h
@@ -37,7 +30,7 @@ surf: ${OBJ}
 
 clean:
 	@echo cleaning
-	@rm -f surf ${OBJ} surf-${VERSION}.tar.gz filters_compiled
+	@rm -f surf ${OBJ} surf-${VERSION}.tar.gz
 
 dist: clean
 	@echo creating dist tarball
